#!/bin/bash -l
#PBS -l walltime=96:00:00,nodes=1:ppn=32,mem=998gb
#PBS -m abe
#PBS -M vanga015@umn.edu
#PBS -q ram1t

cd ~/mlrepo
module load python3
export PATH=$PATH:/home/knightsd/algh0022/sop

bash ./run.embalmer.sh /home/knightsd/public/qiime_db/processed/Yatsunenko_global_gut_study_850_ref_13_8/study_850_split_library_seqs.fna ./yatsunenko PROK_170704
bash ./run.embalmer.sh /home/knightsd/public/qiime_db/processed/Yatsunenko_global_gut_study_850_ref_13_8/study_850_split_library_seqs.fna ./yatsunenko gg97